let titles = [
  "Web Developer",
  "Web Designer",
  "Graphics Designer",
  "Graphics Artist",
  "3D Graphics Artist",
  "Shaders Developer",
  "JavaScript Developer",
  "Ruby Developer",
  "Python Developer",
  "C# Developer",
  "C++ Developer",
  "Java Developer",
  "Game Developer",
  "Software Developer",
  "Software Engineer",
  "Data Scientist",
  "IT Professional",
  "Computer Engineer"
]
